### ISSUE TITLE
Show which mandatory field(s) are not filled/set

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [bihor/fp_masterquiz#33]
Hi,

when a field is mandatory but not filled/set, a generic Javascript message is shown when clicking the next/send button. The user then doesn't know which fields are meant. If forms are big and versatile, it's hard to spot the missing ones. Also, I think a Javascript message, even if that would contain the missing fields, is not state of the art.

Possible solutions:

- Mandatory fields should atleast contain the "required" attribute, so the browser points to the first field which is not filled/set
- Red border or red background in the form field(s) like EXT:powermail or EXT:sf_event_mgt does it.
- Advanced and probably not necessary: Server-side check if the field is valid

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thanks, will do so next week!

**Comment by bihor** [comment]
> Mandatory fields should atleast contain the "required" attribute

HTML5 does not support the required attribute for checkboxes:
https://stackoverflow.com/questions/6218494/using-the-html5-required-attribute-for-a-group-of-checkboxes

I have implemented only the red border.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Much better now, thank you so much! But it doesn't work for textboxes. You forgot 4 things:

- Add condition like with quiz-input https://github.com/bihor/fp_masterquiz/blob/dd88dfbde9ec96de39735422ba6b1db9052a1d3d/Resources/Private/Partials/Question/Properties.html#L78
- Add logic for textboxes [here](https://github.com/bihor/fp_masterquiz/blob/master/Resources/Private/Partials/Quiz/CheckFields.html)
- Add logic for textboxes [here](https://github.com/bihor/fp_masterquiz/blob/master/Resources/Private/Partials/Quiz/CheckForm.html)

- Remove ({question.qmode} == 5) in order to NOT show optional mark if question is mandatory. Probably not related to the red border task but still a bug. :) https://github.com/bihor/fp_masterquiz/blob/dd88dfbde9ec96de39735422ba6b1db9052a1d3d/Resources/Private/Partials/Question/Properties.html#L15

**Comment by bihor** [comment]
Textareas are still optional.
You are right, I should make them mandatory too in the next versions.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Yes, because it doesn't make sense to handle Inputs and Textareas differently when it comes to optional/mandatory attributes. Also keep in mind, that there is an checkbox "optional" in the backend and it seems like a bug if it's not working.

Thanks for the effort.

**Comment by bihor** [comment]
OK, a textarea will be checked in version 3.3.2 too.

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
Thanks, will check it out after my holiday.
